# Generated by Django 4.2.10 on 2024-02-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='type',
            new_name='item_type',
        ),
    ]
