# Generated by Django 4.2.10 on 2024-02-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_rename_item_type_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('perishable', 'PERISHABLE'), ('non-perishable', 'NON_PERISHABLE')], max_length=20),
        ),
    ]
